# The Fraction Unbound in the Brain (Fubrain) Dataset, as described in:
# https://doi.org/10.1021/acs.jcim.9b00180
#
# Download the data from ACS:
# https://pubs.acs.org/doi/suppl/10.1021/acs.jcim.9b00180/suppl_file/ci9b00180_si_002.xlsx
# and convert it to benchmark_data.csv
#
# Additional Comments:
# Original used the two external sets as test, 46 + 25 = 73 total in test set.
# The overall data is 253 points, leaving 180 for training/validation.
# With 10-fold cross validation this equates to 162 (90% of 180) in training
# with the balance in validation, which overall is a 0.64/0.07/0.29 train/val/test split.


# generic args
output_directory: fubrain
random_seed: 12345
problem_type: regression

# featurization
input_file: fubrain/benchmark_data.csv
target_columns: fraction
smiles_column: SMILES
descriptor_set: all
enable_cache: True

# training
number_repeats: 4
number_epochs: 20
batch_size: 256
patience: 2
train_size: 0.64
val_size: 0.07
test_size: 0.29
sampler: random
