# Copy of the flash.yml file, but with a linear model (as a baseline).

fnn_layers: 0
hidden_size: 1613

# generic args
output_directory: flash
random_seed: 195091191
problem_type: regression

# featurization
input_file: flash/benchmark_data.csv
target_columns: flash
smiles_column: smiles
descriptor_set: all

# training
number_repeats: 4
number_epochs: 100
batch_size: 32
patience: 15
train_size: 0.7
val_size: 0.2
test_size: 0.1
sampler: random
