# The Clean Energy Project DataBase (CEPDB) Subset, as described in:
# https://doi.org/10.1021/acsomega.1c02156
#
# This is a subset of the complete database, which can be found here
# https://figshare.com/articles/dataset/moldata_csv/9640427
# and is described in:
# https://doi.org/10.1021/jz200866s
#
# Download the data from the cambridge repository:
# https://www.repository.cam.ac.uk/items/ed46cb03-7c60-43a9-b996-625bc00c72a9
# and decompress it. Rename CEPDB_25000.csv to benchmark_data.csv
#
# From here, you can either run fastprop as-is, or you can run the calculation
# of descriptors separately (suggested for this size dataset & molecules).
# To do so, use a tool like csvtool (or just excel) and copy the SMILES_str
# column into a file on its own (no header). Then run:
# python -m mordred -o precomputed.csv -t smi cepdb_subset.smi
#
# Additional Comments:
# https://pubs.acs.org/doi/10.1021/acsomega.1c02156
# achieved MAE of 0.18 on both validation and test,
# or a 0.06/0.07 MSE

# generic args
output_directory: cepdb_subset
random_seed: 1857987489
problem_type: regression
# run hyperparameter optimization
# optimize: True
# optimized results
fnn_layers: 2
hidden_size: 2200

# featurization
input_file: cepdb_subset/benchmark_data.csv
target_columns: pce
smiles_column: SMILES_str
# if you precomputed the descriptors, use this:
precomputed: cepdb_subset/precomputed.csv
# otherwise, do this:
# descriptors: all
# enable_cache: True

# preprocessing
rescaling: True
zero_variance_drop: False
colinear_drop: False

# training
number_repeats: 1  # 2
number_epochs: 300
batch_size: 40768
patience: 20
train_size: 0.6
val_size: 0.2
test_size: 0.2
sampler: random
