# generic
output_directory: boiling

# featurization
input_file: examples/alkane_boiling.csv
target_columns: boiling_point
smiles_column: py2opsin_smiles

descriptors: all
enable_cache: True

# preprocessing
rescaling: True
zero_variance_drop: False
colinear_drop: False

# training
fnn_layers: 3
learning_rate: 0.0001
batch_size: 2048
number_epochs: 100
problem_type: regression
train_size: 0.6
val_size: 0.2
test_size: 0.2
sampler: random
number_repeats: 5
random_seed: 42
hidden_size: 512

# compare to:
# chemprop_train --data_path examples/chemprop_boiling.csv --dataset_type regression --save_dir chemprop_boiling --metric mae --epochs 200 --split_sizes 60 20 20
