# Copy of the pah.yml file, but with a linear model (as a baseline).

fnn_layers: 0
hidden_size: 1613

# generic args
output_directory: pah
random_seed: 562
problem_type: regression

# featurization
input_file: pah/arockiaraj_pah_data.csv
target_columns: log_p
smiles_column: smiles
descriptor_set: all

# training
number_repeats: 8
number_epochs: 20
batch_size: 64
patience: 5
train_size: 0.8
val_size: 0.1
test_size: 0.1
sampler: random
