# The Organic Crystals in Electronic and Light-Oriented Technologies (Ocelot) Dataset, as described in:
# https://doi.org/10.1039/D2SC04676H
#
# Download the data from the ocelot website:
# https://oscar.as.uky.edu/datasets/
# and unzip it. Rename the csv file to benchmark_data.csv
#
# Additional Comments:
# See https://arxiv.org/abs/2312.13136 for reference performance.

# architecture
# optimize: True
hidden_size: 2600
fnn_layers: 2
# generic
output_directory: ocelot
input_file: ocelot/benchmark_data.csv
target_columns: homo lumo hl vie aie cr1 cr2 hr vea aea ar1 ar2 er s0s1 s0t1
smiles_column: smiles
number_repeats: 3
random_seed: 19
sampler: random
train_size: 0.7
val_size: 0.1
test_size: 0.2

# featurization
descriptors: all
enable_cache: True

# preprocessing
zero_variance_drop: False
colinear_drop: False

# training
learning_rate: 0.0001
batch_size: 20384
number_epochs: 300
patience: 30
