# The Yield Sooting Index (YSI) Dataset, as described in:
# https://doi.org/10.1016/j.combustflame.2017.12.005
#
# Download the data from the GitHub page:
# https://raw.githubusercontent.com/pstjohn/ysi-fragment-prediction/master/ysi.csv
# and rename it to benchmark_data.csv
#
# Additional Comments:
# Reference study did leave-one-out CV and divided the dataset into
# high-YSI and low-YSI subsets, with a Median Absolute Deviation of 2.35 and 28.6
#
# Note that the YSI in this study has been re-scaled by the authors (read the
# paper for more info).


# generic args
output_directory: ysi
random_seed: 987654321
problem_type: regression
# run hyperparameter optimization
# optimize: True
# optimized results
fnn_layers: 4
hidden_size: 2800

# featurization
input_file: ysi/benchmark_data.csv
target_columns: YSI
smiles_column: SMILES
descriptors: all

# preprocessing
rescaling: True
zero_variance_drop: True
colinear_drop: False

# training
number_repeats: 4
number_epochs: 100
batch_size: 1024
patience: 15
train_size: 0.8
val_size: 0.1
test_size: 0.1
sampler: random
