# .github/workflows/paper.yml

name: Convert Paper to PDF
# This workflow is triggered manually or on pushes to the repository.
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'paper/**'
      - 'paper/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDF Engine
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          # the default.latex file used in the paper directory is only suitable for this version
          pandoc-version: '3.1.6'
      - name: Build
        run: |
          cd paper
          pandoc --citeproc -s paper.md -o paper.pdf --template default.latex --pdf-engine=pdflatex --pdf-engine-opt=-output-directory=foo
      - uses: actions/upload-artifact@v1
        with:
          name: paper
          path: paper/paper.pdf
      - uses: actions/upload-artifact@v1
        with:
          name: build_files
          path: paper/foo